baseURL = "https://daelon.net/"
languageCode = "en-us"
title = "daelon.net"
pygmentsUseClasses=true

[params]
  author = "Daelon Suzuka"
  description = "your description"
  keywords = "hugo blog"
  useAvatar = true
  microBlogSection = "posts"
  displayMicroBlog = false
  displayRecent = true
  recentMax = 4
  mail = "daelonsuzuka@gmail.com"
  mainSections = ["posts", "projects"]

[menu]
  [[menu.main]]
    name = "home"
    pre = "<i class=\"fas fa-home fa-sm\"></i>"
    url = "/"
    weight = -9 
  [[menu.main]]
    name = "posts"
    pre = "<i class=\"fas fa-keyboard fa-ms\"></i>"
    url = "/posts/"
    weight = -8
  [[menu.main]]
    name = "tags"
    pre = "<i class=\"fas fa-tags fa-ms\"></i>"
    url = "/tags"
    weight = -7 
  [[menu.main]]
    name = "projects"
    url = "/projects"
    weight = -6 
  [[menu.main]]
    name = "scripts"
    url = "/scripts"
    weight = -6 
  [[menu.main]]
    name = "github"
    pre = "<i class=\"fab fa-github fa-ms\"></i>"
    url = "https://github.com/DaelonSuzuka"
    weight = -2
  [[menu.main]]
    name = "about"
    pre = "<i class=\"far fa-envelope\"></i>"
    url = "/about"
    weight = -1 